### PR TITLE
textfield to filter qrs

### PR DESCRIPTION
**Pull request by stevenh17**
🎟️ Ticket(s): Closes #

👷 Changes: A brief summary of what changes were introduced.
Added a textfield to filter QRs

💭 Notes: Any additional things to take into consideration.

Wait! Before you merge, have you checked the following:

📷 Screenshots
image

(prefer animated gif)

## Checklist

- [ ] Looks good on large screens
- [ ] Looks good on mobile

### CODE REVIEW

**Review by ddennis924 — COMMENTED** [review]
build failing, run npm run lint. And fix any styling errors

**Review by ddennis924 — COMMENTED** [review]
also can you filter by event id and year

**Comment by stevenh17** [comment]
> also can you filter by event id and year

currently it filters by QR["eventID;year"] so should be able to specify year too

**Comment by stevenh17** [comment]
> build failing, run npm run lint. And fix any styling errors

ok ran npm run lint

**Review by ddennis924 — APPROVED** [review]

**Pull request merged**
