### PR TITLE
create new stripe checkout on complete payment

### PR DESCRIPTION
**Pull request by AllanT102**
🎟️ Ticket(s): Closes #

👷 Changes: 
Create new checkout session object every when complete payment is clicked to ensure that user never returns to an expired link. 
Companion does the same

💭 Notes: Any additional things to take into consideration.

Wait! Before you merge, have you checked the following:

📷 Screenshots

(prefer animated gif)

## Checklist

- [ ] Looks good on large screens
- [ ] Looks good on mobile

### CODE REVIEW

**Comment by jerryxu99** [comment]
Do you also mind doing the same thing for complete payment link on Companion? (ppl will be need to complete payment on Companion for produhacks)

also pls still add pictures to show everything works - couple screenshots save a lot of time on the reviewing end

**Review by jerryxu99 — APPROVED** [review]
beaut - @ddennis924 after u merge rhis to dev and before we merge to master we need to test if after payment the companoion page msg changes to Registsered

**Comment by jerryxu99** [comment]
https://github.com/ubc-biztech/serverless-biztechapp/pull/347 merge too

**Review by ddennis924 — COMMENTED** [review]
merge conflicts :(

**Pull request merged**
