### PR TITLE
New event form

### PR DESCRIPTION
**Pull request by dchen150**
Frontend of New Event Form w/ no implementation of Formik/Yup

### CODE REVIEW

**Comment by ianmah** [comment]
If you add new dependencies you should also commit package.json

**Comment by dchen150** [comment]
> If you add new dependencies you should also commit package.json

how do i explicitly commit package.json?

**Comment by dchen150** [comment]
> I'm hijacking this PR, give me a few commits to fix the datepicker

"Add more commits by pushing to the new-event-form branch on ubc-biztech/bt-web." i'm not sure exactly what i need to do

**Comment by ianmah** [comment]
> how do i explicitly commit package.json?

When you install packages with `npm install...` it will modify your package.json file. Then when you do `git add .` it should add it. Or you can do `git add package.json`
Anyways, I already fixed it so its okay this time.

> i'm not sure exactly what i need to do 

I was going to finish off the rest of this PR, so you don't need to do anything

**Pull request merged**
